mvcToDoList/Models/Tarefas.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace TaskList.Models
{
    public class Tarefas
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public DateTime Data { get; set; }
        public string Meta { get; set; }
        public string Status { get; set; }
    }

    public class TodosDBContext : DbContext
    {
        public DbSet<Tarefas> Todo { get; set; }
    }
}

mvcToDoList/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TaskList.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Sobre()
        {
            ViewBag.Message = "Sobre";

            return View();
        }

        public ActionResult Contato()
        {
            ViewBag.Message = "Contato";

            return View();
        }
    }
}

mvcToDoList/Controllers/TarefasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TaskList.Models;

namespace TaskList.Controllers
{
    public class TarefasController : Controller
    {
        private TodosDBContext db = new TodosDBContext();

        // GET: Tarefa
        public ActionResult Index()
        {
            return View(db.Todo.ToList());
        }

        // GET: Tarefa/Detalhes
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarefas tarefas = db.Todo.Find(id);
            if (tarefas == null)
            {
                return HttpNotFound();
            }
            return View(tarefas);
        }

        // GET: Tarefa/Inserir
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tarefa/Inserir
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Data,Meta,Status")] Tarefas tarefas)
        {
            if (ModelState.IsValid)
            {
                db.Todo.Add(tarefas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tarefas);
        }

        // GET: Tarefa/Editar
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarefas tarefas = db.Todo.Find(id);
            if (tarefas == null)
            {
                return HttpNotFound();
            }
            return View(tarefas);
        }

        // POST: Tarefas/Editar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Data,Meta,Status")] Tarefas tarefas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tarefas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tarefas);
        }

        // GET: Tarefa/Excluir
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarefas tarefas = db.Todo.Find(id);
            if (tarefas == null)
            {
                return HttpNotFound();
            }
            return View(tarefas);
        }

        // POST: Tarefa/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tarefas tarefas = db.Todo.Find(id);
            db.Todo.Remove(tarefas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

mvcToDoList/Views/Home/Contato.cshtml
@{
    ViewBag.Title = "Contato";
}

<h3><b>Contato</b></h3><br />
<address>
    <strong>E-mail: </strong> <a target="_blank" href="https://accounts.google.com/signin/v2/sl/pwd?service=mail&passive=true&rm=false&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ss=1&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin">goncalves.lucasmatheus@gmail.com</a><br /><br />
    <strong>LinkedIn:</strong> <a target="_blank" href="https://www.linkedin.com/in/lucas-gon%C3%A7alves-372aa5150/content">Lucas Gonçalves</a><br /><br />
    <strong>Facebook:</strong> <a target="_blank" href="https://www.facebook.com/profile.php?id=100003780731699">Lucas Matheus</a><br /><br />
    <strong>Celular:</strong> <span>(47) 99685-3423</span>
</address>

mvcToDoList/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Página Inicial";
}
<head>
    @Styles.Render("~/Content/Home.css")
</head>
<div class="jumbotron">
    <h1>TASKLIST</h1><br />
    <p class="lead">GERENCIADOR DE TAREFAS</p>
    <p>CRIE TAREFAS COMO META PARA CUMPRIR DURANTE O SEU DIA, SEMANA, MÊS E ANO!</p>
    <p>NO TASKLIST, AINDA EXISTE A OPÇÃO DE EDITAR, EXCLUIR E ADICIONAR DATAS QUE VOCÊ DESEJA EXECUTAR SUA TAREFAS. </p>
    <p class="git"><a target="_blank" href="https://github.com/lucasssg" class="btn btn-primary btn-sm">GitHub - Lucas Gonçalves </a></p>
    @Html.ActionLink("CLIQUE AQUI PARA COMEÇAR!", "Index", "Tarefas", new { area = "" }, new { @class = "navbar-brand expandir" })
</div>

<div class="row">
    <div class="col-md-4">
        <p>
            <b> Projeto by Lucas Gonçalves.</b>
        </p>
     </div>   
</div>

mvcToDoList/Views/Home/Sobre.cshtml
@{
    ViewBag.Title = "Sobre";
}

<h3><b>Lucas Gonçalves</b></h3><br />

<p>Formado em Técnico de Informática e cursando superior de Tecnologia em Sistemas para Internet.</p>
<p>21 anos, nascido em Blumenau - Santa Catarina.</p>

<style>
    p{
        font-family: Arial;
        font-size: 16px;
    }
</style>

mvcToDoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title</title>

        @Styles.Render("~/Content/Site.css")
        @Styles.Render("~/Content/justified-nav.css")
        @Scripts.Render("~/bundles/modernizr")

    </head>
    <body>
        <div class="container">
            <div class="navbar navbar-default">
                <ul class="nav navbar-nav">
                    <li class="menu">@Html.ActionLink("PÁGINA INICIAL", "Index", "Home")</li>
                    <li class="menu">@Html.ActionLink("SOBRE", "Sobre", "Home")</li>
                    <li class="menu">@Html.ActionLink("CONTATO", "Contato", "Home")</li>
                    <li class="menu tarefas">@Html.ActionLink("TAREFAS", "Index", "Tarefas")</li>
                </ul>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p><b>&copy; @DateTime.Now.Year - TaskList</b></p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>

mvcToDoList/Views/Tarefas/Create.cshtml
@model TaskList.Models.Tarefas

@{
    ViewBag.Title = "Criar Tarefa";
}

<h2><b>ADICIONAR</b></h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tarefa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Descrição Tarefa:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input title="Informe a descrição da tarefa" required @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, "Defina uma data:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Meta, "Pessoal ou Trabalho?", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Meta, new SelectList(
                  new List<Object>{
                       new { value = "Pessoal" , text = "Pessoal"  },
                       new { value = "Trabalho" , text = "Trabalho" },
                 
                    },
                  "value",
                  "text",
                   1))

                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, " Pendente ou Concluído? ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
              @Html.DropDownListFor(model => model.Status, new SelectList(
                  new List<Object>{
                       new { value = "PENDENTE" , text = "PENDENTE" },
                       new { value = "CONCLUÍDO" , text = "CONCLUÍDO"  }
                    },
                  "value",
                  "text",
                   2))

                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="SALVAR" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

mvcToDoList/Views/Tarefas/Delete.cshtml
@model TaskList.Models.Tarefas

@{
    ViewBag.Title = "Remover Tarefa";
}

<h2><b>REMOVER</b></h2>

<h3>Tem certeza que deseja remover essa tarefa?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Meta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Meta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="REMOVER" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

mvcToDoList/Views/Tarefas/Details.cshtml
@model TaskList.Models.Tarefas

@{
    ViewBag.Title = "Detalhes da Tarefa";
}

<h2><b>DETALHES</b></h2>

<div>
    <h4>Tarefa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Meta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Meta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Voltar", "Index")
</p>

mvcToDoList/Views/Tarefas/Edit.cshtml
@model TaskList.Models.Tarefas

@{
    ViewBag.Title = "Editar Tarefa";
}

<h2><b>EDITAR</b></h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tarefa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input title="Informe a descrição da tarefa" required @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Meta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Meta, new SelectList(
                 new List<Object>{
                      new { value = "Pessoal" , text = "Pessoal"  },
                      new { value = "Trabalho" , text = "Trabalho" },

                   },
                 "value",
                 "text",
                  1))

                @Html.ValidationMessageFor(model => model.Meta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Status, new SelectList(
                 new List<Object>{
                      new { value = "PENDENTE" , text = "PENDENTE" },
                      new { value = "CONCLUÍDO" , text = "CONCLUÍDO"  }
                   },
                 "value",
                 "text",
                  2))

                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="SALVAR" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

mvcToDoList/Views/Tarefas/Index.cshtml
@model IEnumerable<TaskList.Models.Tarefas>

@{
    ViewBag.Title = "Minhas Tarefas";
}

<h2><b>Lista de Tarefas</b></h2><br />

<p>
    @Html.ActionLink("Nova Tarefa", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Data)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Meta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Meta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.ID }) |
            @Html.ActionLink("Excluir", "Delete", new { id=item.ID })
        </td>
    </tr>
}
</table>

<style>
    body{
        font-family: Arial;
    }
</style>